# Generated by Django 6.0 on 2025-12-30 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('land_lat', models.FloatField()),
                ('land_lon', models.FloatField()),
                ('weather_summary_snapshot', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_extracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
                ('precipitation', models.FloatField(null=True)),
                ('temp_max', models.FloatField(null=True)),
                ('temp_min', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('radiation', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude', 'date'], name='data_weathe_latitud_69b729_idx')],
                'unique_together': {('latitude', 'longitude', 'date')},
            },
        ),
    ]
