# Generated by Django 6.0 on 2025-12-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ph', models.FloatField(null=True)),
                ('organic_carbon_pct', models.FloatField(null=True)),
                ('bulk_density', models.FloatField(null=True)),
                ('texture', models.CharField(max_length=20)),
                ('source', models.CharField(default='SoilGrids', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
    ]
