# Generated by Django 6.0 on 2026-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_soilcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextractionlog',
            name='soil_summary_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
