# Generated by Django 6.0 on 2026-02-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_add_soil_summary_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextractionlog',
            name='api_source',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='dataextractionlog',
            name='confidence',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='clay_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='sand_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='silt_pct',
            field=models.FloatField(null=True),
        ),
    ]
