# Generated by Django 5.2.16 on 2026-08-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_dataextractionlog_api_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataextractionlog',
            name='api_source',
        ),
        migrations.RemoveField(
            model_name='dataextractionlog',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='soilcache',
            name='clay_pct',
        ),
        migrations.RemoveField(
            model_name='soilcache',
            name='sand_pct',
        ),
        migrations.RemoveField(
            model_name='soilcache',
            name='silt_pct',
        ),
        migrations.AlterField(
            model_name='dataextractionlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soilcache',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weathercache',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
