# Generated by Django 5.2.16 on 2026-09-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_update_caching_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilcache',
            name='available_k',
            field=models.FloatField(blank=True, help_text='Available potassium (kg/ha)', null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='available_p',
            field=models.FloatField(blank=True, help_text='Available phosphorus (kg/ha)', null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='cec',
            field=models.FloatField(blank=True, help_text='Cation Exchange Capacity at pH 7 (cmol(+)/kg)', null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='clay_pct',
            field=models.FloatField(blank=True, help_text='Clay fraction percentage (<2 um)', null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='coarse_fragments_pct',
            field=models.FloatField(blank=True, help_text='Coarse fragments volume percentage (>2mm)', null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='salinity_ec',
            field=models.FloatField(blank=True, help_text='Electrical conductivity (dS/m)', null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='sand_pct',
            field=models.FloatField(blank=True, help_text='Sand fraction percentage (50-2000 um)', null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='silt_pct',
            field=models.FloatField(blank=True, help_text='Silt fraction percentage (2-50 um)', null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='total_nitrogen',
            field=models.FloatField(blank=True, help_text='Total nitrogen (g/kg)', null=True),
        ),
        migrations.AddField(
            model_name='soilcache',
            name='zinc_ppm',
            field=models.FloatField(blank=True, help_text='Available zinc (ppm)', null=True),
        ),
        migrations.AlterField(
            model_name='soilcache',
            name='bulk_density',
            field=models.FloatField(blank=True, help_text='Bulk density of fine earth (g/cm³)', null=True),
        ),
        migrations.AlterField(
            model_name='soilcache',
            name='organic_carbon_pct',
            field=models.FloatField(blank=True, help_text='Soil Organic Carbon (mass %)', null=True),
        ),
        migrations.AlterField(
            model_name='soilcache',
            name='ph',
            field=models.FloatField(blank=True, help_text='Soil pH (1:5 H2O suspension)', null=True),
        ),
        migrations.AlterField(
            model_name='soilcache',
            name='texture',
            field=models.CharField(help_text='USDA texture class (e.g., loamy, clayey, sandy)', max_length=20),
        ),
    ]
