# Generated by Django 6.0 on 2025-12-29 11:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Spatial point (longitude, latitude)', srid=4326)),
                ('area_ha', models.FloatField(blank=True, help_text='Total land area in hectares', null=True)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='GIS Polygon defining the land boundary', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the land record was initialized')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(help_text='Algorithmically determined boundary geometry', srid=4326)),
                ('area_ha', models.FloatField(help_text='Calculated area of the suggested shape')),
                ('confidence', models.FloatField(help_text='Probability score (0.0 to 1.0) of the detection accuracy')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='lands.land')),
            ],
        ),
    ]
